version: 2.1
aliases:
  node: &node
    docker:
      - image: circleci/node:10

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - node-modules-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: |
        yarn

  persist_node_modules: &persist_node_modules
    save_cache:
      name: Save node modules cache
      key: node-modules-{{ checksum "yarn.lock" }}
      paths:
        - node_modules

  attach_to_bootstrap: &attach_to_bootstrap
    attach_workspace:
      at: .

commands:
  run_command:
    parameters:
      command:
        type: string
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *attach_to_bootstrap
      - run: yarn "<< parameters.command >>"

jobs:
  bootstrap:
    <<: *node
    steps:
      - checkout
      - <<: *restore_node_modules
      - <<: *install_node_modules
      - <<: *persist_node_modules
      - run: yarn bootstrap
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  test:
    <<: *node
    steps:
      run_command:
        command: test

workflows:
  version: 2
  build_test:
    jobs:
      - bootstrap
      - test:
          requires:
            - bootstrap
